$ErrorActionPreference = 'Stop'

$NAMESPACE = 'leojonathanoh'

$BASE_DIR = $PSScriptRoot
$MODULE_NAME = (Get-Item $BASE_DIR).Name
$APP_DIR = "$BASE_DIR/app"
$APP_MODULE_DIR = "$APP_DIR/$MODULE_NAME"
$APP_MODULE_PUBLIC_DIR = "$APP_MODULE_DIR/public"
$APP_MODULE_PRIVATE_DIR = "$APP_MODULE_DIR/private"
$APP_MODULE_HELPER_DIR = "$APP_MODULE_DIR/helper"
$RELEASE_DIR = "$BASE_DIR/release"
$TEST_DIR = "$BASE_DIR/test"
$PUBLISH_DIR = "$BASE_DIR/publish"
$PUBLISH_PSGALLERY_DIR = "$PUBLISH_DIR/psgallery"

$MODULE_VERSION = '1.0.0'
$MODULE_MANIFEST_FILE = "$APP_MODULE_DIR/$MODULE_NAME.psd1"

